### ISSUE TITLE
not working -> File "driver.py", line 50

### ISSUE THREAD

**Issue by Oshekher** [RahulShaw/ITPROTV-DL#4]
File "driver.py", line 50
    chrome_options.add_argument(f'user-agent={user_agent}')
                                                         ^
SyntaxError: invalid syntax

@RahulShaw

**Comment by saikek** [comment]
1) replace with:
```
chrome_options.add_argument("user-agent={}".format(user_agent))
```
2) rather use venv to avoid deps issues:
```
python3 -m venv .
source bin/activate
...
install dependencies
```

**Comment by saikek** [comment]
4) Make sure that driver matches chrome version
5) remove all entries starting from `www.` from cookies.txt

**Comment by retardedloozer** [comment]
> 1. Make sure that driver matches chrome version
> 2. remove all entries starting from `www.` from cookies.txt

This helped me fix my problem with cookie domain mismatch. I hope if someone has the same issue, they can stumble across this issue as it fixed it for me.
